<?php
/**
 * @var  \NiceForNow\HairCare\Block\Index $block
 */
$getCondition = $block->getCondition();
$getSubCondition = $block->getSubCondition();
//$getPostCollection = $block->getPostCollection("condition");
$getPostCollection = [];
?>
<form id="form" name="form" method="post">
    <label for=1">Điều kiện 1 </label>
    <select name="condition1" id="condition1" class="form-control" id="">
        <?php foreach ($getCondition as $select) {
    ?>
            <option value="<?= $select['condition_id']; ?>" check><?= $select['name']; ?></option>";
            <?php
}
        ?>
    </select>
    <label for=1">Điều kiện 2 </label>
    <select name="condition2" id="condition2" class="form-control" name>
        <?php foreach ($getSubCondition as $select) {
            ?>
            <option value="<?= $select['sub_id']; ?>"><?= $select['name']; ?></option>";
            <?php
        }
        ?>
    </select>
    <input type="button" name="submit" id="btn-submit" value="Submit">
</form>
<div id="container"></div>

    <table>
        <div id="myDIV">
        <tbody>
        <?php foreach ($getPostCollection as $type => $item): ?>
            <tr>
                <td rowspan="<?= count($item) ?>"><?= $type ?></td>

                <?php foreach ($item as $idx => $subitem): ?>
                    <?php if ($idx == 0): ?>
                        <td><h4><?=$subitem['title'] ?></h4><?= $subitem['description'] ?></td>
                    <?php else: ?>
                        <td><?= $subitem['title'] ?></h4><?= $subitem['description'] ?></td>
                    <?php endif; ?>

                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin-top: 30px;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: center;
        padding: 8px;
    }
</style>

<script>

    require(["jquery"], function ($) {
        $(document).ready(function () {
            $("#myDIV").hide();

            $("#btn-submit").on('click', function () {
                var condition1 = document.getElementById("condition1").value;
                var condition2 = document.getElementById("condition2").value;
                var url = "<?= $block->getUrl('haircare/index/result')?>";
                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        isAjax: 1,
                        condition1: condition1,
                        condition2: condition2,
                    }
                }).done(function (result) {
                    $("#myDIV").show();
                    // var array = $.map(result, function (value, index) {
                    //     return [value];
                    // });

                    $('#container').append(
                        ` <thead>
                                <tr>
                                    <th>Type</th>
                                    <th>Content</th>
                                </tr>
                         </thead>`);

                    var a = "";
                    $.each( result, function(item,types) {
                        a += `<tbody>
                                <tr>
                                    <td rowspan='2'>${item}</td>
                                `

                        $.each(types, function (idx,subitem) {

                         a +=`<td><h4>${subitem['title']}</h4> ${subitem['description']}</td>
                                </tr>
                               <tbody>
                               `;
                        })
                        });
                    $('#container').html(a);

                }).error(function (result) {

                });
            });
        });
    });

</script>