<?php
/**
 * @var  \NiceForNow\HairCare\Block\Index $block
 */
$getCondition = $block->getCondition();
$getSubCondition = $block->getSubConditionByID();
$getPostCollection = $block->getListNews()->getdata();
$dataRenderer = [];
foreach ($getPostCollection as $datum) {
    $dataRenderer[$datum['type']][] = $datum;
}
?>
<form id="form" name="form" method="get">
    <div id="condition">
        <label for=1">Condition 1</label>
        <select name="condition1" id="condition1" class="target" id="condition1">
            <option value="0"><?= "please choose conditon" ?></option>
            <?php foreach ($getCondition as $select) : ?>
                <?php if ($select['condition_id'] == $block->getCheckedSelect()): ?>
                    <option class="option" value="<?= /* @noEscape */
                    $select['condition_id']; ?>" selected="selected">
                        <?= /* @noEscape */
                        $select['name']; ?>
                    </option>";
                <?php else: ?>
                    <option class="option" value="<?= /* @noEscape */
                    $select['condition_id']; ?>">
                        <?= /* @noEscape */
                        $select['name']; ?>
                    </option>";
                <?php endif; ?>
            <?php endforeach; ?>
        </select>
    </div>
    <div id="sub"></div>
</form>
<div class="form-result">

    <?php if ($dataRenderer && count($dataRenderer)): ?>

        <?php foreach ($dataRenderer as $type => $item):; ?>

            <div style="display: block" class="block-form">
                <div class="big-title"><h2><?= /* @noEscape */
                    $block->getType($type) ?></div>
                <div class="content">
                    <?php foreach ($item as $idx => $subitem):; ?>
                        <?php if ($idx == 0): ?>
                            <h4><?= /* @noEscape */
                        $subitem['title'] ?></h4><?= /* @noEscape */
                            $subitem['description'] ?>
                        <?php else: ?>
                            <h4><?= /* @noEscape */
                        $subitem['title'] ?></h4><?= /* @noEscape */
                            $subitem['description'] ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endforeach; ?>
        <div class="show-page">
        <?php if ($block->getPagerHtml()): ?>
            <?= /* @noEscape */
            $block->getPagerHtml(); ?>
        <?php endif; ?>
    <?php else: ?>
        <div class="rsgitech-no-records">
            <?= /* @noEscape */
            __('News not available'); ?>
        </div>
        </div>
    <?php endif; ?>

</div>

<script>
    require(["jquery"], function ($) {
        $(document).ready(function () {
            let value1 = $("#condition1").val();
            if (!isNaN(parseInt(value1))) {
                LoadAjax(value1);
            }
            $(".target").change(function () {
                var value = $("#condition1").val();
                LoadAjax(value);
            });

            function LoadAjax(value) {
                var value = $("#condition1").val();
                var url = "<?= /* @noEscape */$block->getUrl('haircare/index/getajax')?>";
                $.ajax({
                    type: "POST",
                    url: url,
                    dataType: "html",
                    data: {
                        id: value,
                        sub_id:<?= /* @noEscape */$block->getParamSub();?>
                    },
                    success: function (response) {
                        $('#sub').html(response);

                    },
                    error: function () {
                    }
                });

            }
        });
    })
</script>
